name: Node.js Package
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v2
        with:
          node-version: '18.x'
      - run: pnpm install
      - run: pnpm test

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v2
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
